const movieList = [
    {
        "Id" : 1,
        "Owner": "Netflix Originals",
        "Name": "STRANGER THINGS",
        "Rating": "95%",
        "ReleaseYear": "2017",
        "SeasonCount": "2 Seasons",
        "IMDB": "5.1",
        "HighestQuality": "4K Ultra HD",
        "StoryLine": "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
        "Producerslist": "Winona Ryder, David Harbour, Matthew Modine",
        "Type": ["TV Shows", "TV Sci-Fi & Fantasy", "Teen TV Shows"],
        "ImgUrl": "https://www.denofgeek.com/wp-content/uploads/2022/05/Stranger-Things-Season-3-poster-cropped.jpeg?resize=768%2C432",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
    },
    {
        "Id" : 2,
        "Owner": "Netflix Original",
        "Name": "Flowers in the Attic",
        "Rating": "95%", "ReleaseYear": "1992",
        "SeasonCount": "3 Seasons",
        "IMDB": "6.4",
        "HighestQuality": "1080P",
        "StoryLine": "In a post-apocalyptic world",
        "Producerslist": "Sergei Pawling",
        "Type": "Drama|Mystery|Thriller",
        "ImgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuNMhRkVBrLRQsLIDDoRO_A_h96FXgNA3Pvw&s",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
    },
    {
        "Id" : 3,
        "Owner": "Netflix Original",
        "Name": "Charlie: The Life and Art of Charles Chaplin",
        "Rating": "91%",
        "ReleaseYear": "1994",
        "SeasonCount": "4 Seasons",
        "IMDB": "1.1",
        "HighestQuality": "1080P",
        "StoryLine": "A group of rebels fight against a tyrannical government to restore freedom",
        "Producerslist": "Karlan Schaben",
        "Type": "Documentary",
        "ImgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs6ls8tldTPTWEyWVNemIEB49eWmgYeZDFrw&s",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4"
    },
    {
        "Id" : 4,
        "Owner": "Netflix Original",
        "Name": "Brain on fire",
        "Rating": "91%",
        "ReleaseYear": "2006",
        "SeasonCount": "1 Seasons",
        "IMDB": '1.6',
        "HighestQuality": "HDR",
        "StoryLine": "An ancient prophecy foretells of a hero who will defeat the dark lord",
        "Producerslist": "Gasper Dominguez",
        "Type": "Horror|Sci-Fi",
        "ImgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT687iUCHVNzEk83yZF31rGsg_hv6CvP5gZCA&s",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4"
    },
    {
        "Id" : 5,
        "Owner": "Netflix Original",
        "Name": "Asoka (Ashoka the Great)",
        "Rating": "97%",
        "ReleaseYear": "1998",
        "SeasonCount": "4 Seasons",
        "IMDB": "4.8",
        "HighestQuality": "HDR",
        "StoryLine": "A scientist creates a sentient AI that threatens to destroy humanity",
        "Producerslist": "Cristen Szanto",
        "Type": "Action|Drama|Romance",
        "ImgUrl": "https://dooleyonline.typepad.com/.a/6a00e551a4e0f388330192acc62bc9970d-pi",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4"
    },
    {
        "Id" : 6,
        "Owner": "Netflix Original",
        "Name": "Evilspeak",
        "Rating": "92%",
        "ReleaseYear": "2013",
        "SeasonCount": '3 Seasons',
        "IMDB": "7.5",
        "HighestQuality": "4K Ultra Hd",
        "StoryLine": "A group of friends discover a hidden treasure map and set off on an adventure",
        "Producerslist": "Alexia Beakes",
        "Type": "Horror|Sci-Fi",
        "ImgUrl": "https://chicagofilmscene.com/wp-content/uploads/2020/10/Evilspeak-2.jpg",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4"
    },
    {
        "Id" : 7,
        "Owner": "Netflix Original",
        "Name": "Cantante, El",
        "Rating": "97%",
        "ReleaseYear": "2010",
        "SeasonCount": '5 Seasons',
        "IMDB": "3.5",
        "HighestQuality": "4K Ultra Hd",
        "StoryLine": "A group of survivors must navigate a post-apocalyptic wasteland to find a new home",
        "Producerslist": "Gerri Hamper",
        "Type": "Drama|Musical",
        "ImgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR59dVU4J5SaviDY9eyzJgiCSAg97D-2M4bg&s",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
    },
    {
        "Id" : 8,
        "Owner": "Netflix Original",
        "Name": "Judgment Night",
        "Rating": "95%",
        "ReleaseYear": "1994",
        "SeasonCount": "2 Seasons",
        "IMDB": "1.1",
        "HighestQuality": "HDR",
        "StoryLine": "A group of time travelers must prevent a catastrophic event from altering the timeline",
        "Producerslist": "Teddy Sturror",
        "Type": "Action|Crime|Thriller",
        "ImgUrl": "https://facts.net/wp-content/uploads/2023/10/40-facts-about-the-movie-judgment-night-1698314176.jpg",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
    },
    {
        "Id" : 9,
        "Owner": "Netflix Original",
        "Name": "Artemisia",
        "Rating": "91%",
        "ReleaseYear": "2009",
        "SeasonCount": "4 Seasons",
        "IMDB": "7.5",
        "HighestQuality": "HDR",
        "StoryLine": "The hero embarks on a quest to save the kingdom from an evil sorcerer",
        "Producerslist": "Josiah Angric",
        "Type": "Drama",
        "ImgUrl": "https://i.pinimg.com/originals/1d/40/c8/1d40c85699ef4d47894169c83e30b2aa.jpg",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4"
    },
    {
        "Id" : 10,
        "Owner": "Netflix Original",
        "Name": "Army Brats (Schatjes!)",
        "Rating": "96%",
        "ReleaseYear": "1985",
        "SeasonCount": "5 Seasons",
        "IMDB": "9.9",
        "HighestQuality": "4K Ultra Hd",
        "StoryLine": "A group of hackers uncover a government conspiracy that threatens freedom",
        "Producerslist": "Tedra Chadwick",
        "Type": "Children|Comedy",
        "ImgUrl": "https://m.media-amazon.com/images/M/MV5BMmQ1OWRmYmQtNGY2MC00MDA2LWIxZmMtOTk0ZTIyMWRkZDhiXkEyXkFqcGdeQXVyMTUxODIyNzk@._V1_FMjpg_UX1000_.jpg",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
    },
    {
        "Id" : 11,
        "Owner": "Netflix Original",
        "Name": "Two Guys Talkin' About Girls",
        "Rating": "93%",
        "ReleaseYear": "1999",
        "SeasonCount": "4 Seasons",
        "IMDB": "3.8",
        "HighestQuality": "1080P",
        "StoryLine": "A group of time travelers must prevent a catastrophic event from altering the timeline",
        "Producerslist": "Angie Hulburd",
        "Type": "Comedy|Drama|Romance",
        "ImgUrl": "https://m.media-amazon.com/images/S/pv-target-images/4eea791a57b2ba8950573d8c619c760aaea2994e11caf460324eac3c7f61f221.jpg",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
    },
    {
        "Id" : 12,
        "Owner": "Netflix Originals",
        "Name": "THE WITCHER",
        "Rating": "92%",
        "ReleaseYear": "2019",
        "SeasonCount": "2 Seasons",
        "IMDB": "8.2",
        "HighestQuality": "4K Ultra HD",
        "StoryLine": "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
        "Producerslist": "Henry Cavill, Freya Allan, Anya Chalotra",
        "Type": ["TV Shows", "Fantasy TV Shows", "TV Dramas"],
        "ImgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3zGrzXYCJkekNjLztZPg7_TsxXoDTLcX6kw&s",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4"
    },
    {
        "Id" : 13,
        "Owner": "Netflix Originals",
        "Name": "HOUSE OF CARDS",
        "Rating": "85%",
        "ReleaseYear": "2013",
        "SeasonCount": "6 Seasons",
        "IMDB": "8.7",
        "HighestQuality": "HD",
        "StoryLine": "A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.",
        "Producerslist": "Kevin Spacey, Robin Wright",
        "Type": ["TV Shows", "Political TV Shows", "TV Dramas"],
        "ImgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3sb1Cn9SR6SRlc0pceGvWNlF3z89B_Jb2Og&s",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4"
    },
    {
        "Id" : 14,
        "Owner": "Amazon Prime",
        "Name": "THE BOYS",
        "Rating": "91%",
        "ReleaseYear": "2019",
        "SeasonCount": "3 Seasons",
        "IMDB": "8.7",
        "HighestQuality": "4K Ultra HD",
        "StoryLine": "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.",
        "Producerslist": "Karl Urban, Jack Quaid, Antony Starr",
        "Type": ["TV Shows", "Action & Adventure", "TV Dramas"],
        "ImgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQilef3yD0mh_83bKeAq7z7N5Dn9evuCOHOBQ&s",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
    },
    {
        "Id" : 15,
        "Owner": "Hulu",
        "Name": "THE HANDMAID'S TALE",
        "Rating": "89%",
        "ReleaseYear": "2017",
        "SeasonCount": "4 Seasons",
        "IMDB": "8.4",
        "HighestQuality": "HD",
        "StoryLine": "Set in a dystopian future, a woman is forced to live as a concubine under a fundamentalist theocratic dictatorship.",
        "Producerslist": "Elisabeth Moss, Yvonne Strahovski",
        "Type": ["TV Shows", "Sci-Fi & Fantasy", "TV Dramas"],
        "ImgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQN3uc69tPR3FRtMfiPzzbvrIabqTX7T6Mwg&s",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
    },
    {
        "Id" : 16,
        "Owner": "Netflix Originals",
        "Name": "BLACK MIRROR",
        "Rating": "93%",
        "ReleaseYear": "2011",
        "SeasonCount": "5 Seasons",
        "IMDB": "8.8",
        "HighestQuality": "4K Ultra HD",
        "StoryLine": "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.",
        "Producerslist": "Daniel Lapaine, Hannah John-Kamen, Michaela Coel",
        "Type": ["TV Shows", "Sci-Fi & Fantasy", "TV Thrillers"],
        "ImgUrl": "https://m.media-amazon.com/images/M/MV5BZTgyNTBkNzctN2I3NC00NTA1LWJiMDMtYzA2MmYyZjc1NWQzXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
    },
    {
        "Id" : 17,
        "Owner": "Disney+",
        "Name": "THE MANDALORIAN",
        "Rating": "90%",
        "ReleaseYear": "2019",
        "SeasonCount": "3 Seasons",
        "IMDB": "8.8",
        "HighestQuality": "4K Ultra HD",
        "StoryLine": "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
        "Producerslist": "Pedro Pascal, Gina Carano",
        "Type": ["TV Shows", "Action & Adventure", "Sci-Fi & Fantasy"],
        "ImgUrl": "https://cdn.europosters.eu/image/hp/50758.jpg",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4"
    },
    {
        "Id" : 18,
        "Owner": "Netflix Originals",
        "Name": "NARCOS",
        "Rating": "89%",
        "ReleaseYear": "2015",
        "SeasonCount": "3 Seasons",
        "IMDB": "8.8",
        "HighestQuality": "HD",
        "StoryLine": "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar.",
        "Producerslist": "Pedro Pascal, Wagner Moura",
        "Type": ["TV Shows", "Crime TV Shows", "TV Dramas"],
        "ImgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQIZDO7RoSXBMh5dx_VN5WIIF876NvOkvEQg&s",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
    },
    {
        "Id" : 19,
        "Owner": "HBO Max",
        "Name": "GAME OF THRONES",
        "Rating": "85%",
        "ReleaseYear": "2011",
        "SeasonCount": "8 Seasons",
        "IMDB": "9.2",
        "HighestQuality": "4K Ultra HD",
        "StoryLine": "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
        "Producerslist": "Emilia Clarke, Peter Dinklage",
        "Type": ["TV Shows", "Fantasy TV Shows", "TV Dramas"],
        "ImgUrl": "https://cdn.europosters.eu/image/hp/65920.jpg",
        "Trailer" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
    },
]

export default movieList